# ==== black ====
[tool.black]
line-length = 79
target-version = ['py311']


# ==== isort ====
[tool.isort]
profile = "black"
line_length = 79
known_first_party = [
    "hows_my_turns",
    "config",
]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]


# ==== mypy ====
[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = [
    "mypy_django_plugin.main",
]
